{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\", autouse=True)\n    def mssql_connector():\n        \"\"\"\n        Fixture to create MSSQLConnector instance.\n        \"\"\"\n        mssql_connector = MSSQLConnector()\n>       mssql_connector.connect()\n\ntests\\suites\\conftest.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <utils.db.db_utils.MSSQLConnector object at 0x000001604F5F2410>\n\n    def connect(self):\n>       self.conn = pyodbc.connect(self.connection_str)\nE       pyodbc.OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.\\r\\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 18 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to 127.0.0.1,5433. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')\n\nutils\\db\\db_utils.py:24: OperationalError\n", "test_name": "test_user_can_submit_an_order", "rerun": "0"}}, "suite_name": "tests/suites/test_order_management_suite.py"}}}, "date": "March 17, 2023", "start_time": 1679013599.6638086, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}