{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\n       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x000001EE9F969240>, 'Connection to host.docker.internal timed out. (connect timeout=None)')\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=5105): Max retries exceeded with url: /Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dtoken%26client_id%3Dorderingswaggerui%26redirect_uri%3Dhttp%253A%252F%252Fhost.docker.internal%253A5102%252Fswagger%252Foauth2-redirect.html%26scope%3Dorders%26state%3DTW9uIE1hciAwNiAyMDIzIDE1OjI5OjA4IEdNVCswMjAwIChJc3JhZWwgU3RhbmRhcmQgVGltZSk%253D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EE9F969240>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))\n               requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='host.docker.internal', port=5105): Max retries exceeded with url: /Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dtoken%26client_id%3Dorderingswaggerui%26redirect_uri%3Dhttp%253A%252F%252Fhost.docker.internal%253A5102%252Fswagger%252Foauth2-redirect.html%26scope%3Dorders%26state%3DTW9uIE1hciAwNiAyMDIzIDE1OjI5OjA4IEdNVCswMjAwIChJc3JhZWwgU3RhbmRhcmQgVGltZSk%253D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EE9F969240>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))\n", "test_name": "test_mss", "rerun": "0"}}, "suite_name": "tests/suites/test_order_management_suite.py"}}}, "date": "March 18, 2023", "start_time": 1679130159.0995877, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}